load("@gazelle//:def.bzl", "gazelle_binary", "gazelle_generation_test")
load("@rules_go//go:def.bzl", "go_library", "go_test")

exports_files(["defs.bzl"])

go_library(
    name = "css",
    srcs = [
        "config.go",
        "configure.go",
        "generate.go",
        "imports.go",
        "kinds.go",
        "language.go",
        "resolve.go",
    ],
    importpath = "github.com/perplexityai/gazelle_css/css",
    visibility = ["//visibility:public"],
    deps = [
        "@gazelle//config",
        "@gazelle//label",
        "@gazelle//language",
        "@gazelle//repo",
        "@gazelle//resolve",
        "@gazelle//rule",
    ],
)

go_test(
    name = "css_test",
    srcs = [
        "configure_test.go",
        "imports_test.go",
        "kinds_test.go",
        "language_test.go",
    ],
    embed = [":css"],
    deps = [
        "@gazelle//config",
        "@gazelle//language",
        "@gazelle//resolve",
        "@gazelle//rule",
    ],
)

gazelle_binary(
    name = "gazelle_test_binary",
    languages = [":css"],
    visibility = ["//visibility:private"],
)

gazelle_generation_test(
    name = "gazelle_generation_test",
    gazelle_binary = ":gazelle_test_binary",
    gazelle_timeout_seconds = 60,
    test_data = glob(["testdata/**"]),
)
