package css

import (
	"fmt"
	"path"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const ignoreBuildGuidance = "configure distinct CSS target names, rename the existing rule, or add # gazelle:ignore to prevent Gazelle from modifying this entire BUILD file"

func validateCSSModulePackageSources(moduleSrcs []string) error {
	for _, src := range moduleSrcs {
		if strings.Contains(src, "/") {
			return fmt.Errorf(
				"CSS Module source %q is below this Bazel package; add %s/BUILD.bazel so the directory has its own CSS Module target",
				src,
				path.Dir(src),
			)
		}
	}
	return nil
}

func hasExistingCSSModuleRule(c *config.Config, f *rule.File) bool {
	if f == nil {
		return false
	}
	for _, r := range f.Rules {
		if kindMatches(c, r.Kind(), cssModuleKind) {
			return true
		}
	}
	return false
}

func validateCSSModuleOwnership(c *config.Config, f *rule.File, otherGen []*rule.Rule, moduleName, libraryName string, generatesLibrary bool, retiringLibrary *rule.Rule) error {
	if generatesLibrary && moduleName == libraryName {
		return fmt.Errorf(
			"%s and %s would both generate target %q; %s",
			cssLibraryKind,
			cssModuleKind,
			moduleName,
			ignoreBuildGuidance,
		)
	}
	for _, r := range otherGen {
		if kindMatches(c, r.Kind(), cssModuleKind) {
			return fmt.Errorf(
				"%s(name = %q) is already generated by another language; %s",
				r.Kind(),
				r.Name(),
				ignoreBuildGuidance,
			)
		}
		if r.Name() == moduleName {
			return fmt.Errorf(
				"target %q is already owned by %s; %s",
				moduleName,
				r.Kind(),
				ignoreBuildGuidance,
			)
		}
	}
	var managedRules []*rule.Rule
	if f == nil {
		return nil
	}
	for _, r := range f.Rules {
		if r == retiringLibrary {
			continue
		}
		if kindMatches(c, r.Kind(), cssModuleKind) {
			managedRules = append(managedRules, r)
			continue
		}
		if r.Name() == moduleName {
			return fmt.Errorf(
				"target %q is already owned by %s; %s",
				moduleName,
				r.Kind(),
				ignoreBuildGuidance,
			)
		}
	}
	if len(managedRules) > 1 {
		return fmt.Errorf(
			"multiple CSS Module rules exist; expected one aggregate target %q; %s",
			moduleName,
			ignoreBuildGuidance,
		)
	}
	if len(managedRules) == 1 && managedRules[0].Name() != moduleName {
		r := managedRules[0]
		return fmt.Errorf(
			"%s(name = %q) does not use the configured name %q; %s",
			r.Kind(),
			r.Name(),
			moduleName,
			ignoreBuildGuidance,
		)
	}
	return nil
}
